//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stomatologiya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Производитель.
    /// </summary>
    // *** Start programmer edit section *** (Производитель CustomAttributes)

    // *** End programmer edit section *** (Производитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроизводительE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("ПроизводительL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class Производитель : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Производитель CustomMembers)

        // *** End programmer edit section *** (Производитель CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Производитель.Код CustomAttributes)

        // *** End programmer edit section *** (Производитель.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Производитель.Код Get start)

                // *** End programmer edit section *** (Производитель.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Производитель.Код Get end)

                // *** End programmer edit section *** (Производитель.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Производитель.Код Set start)

                // *** End programmer edit section *** (Производитель.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Производитель.Код Set end)

                // *** End programmer edit section *** (Производитель.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Производитель.Наименование CustomAttributes)

        // *** End programmer edit section *** (Производитель.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Производитель.Наименование Get start)

                // *** End programmer edit section *** (Производитель.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Производитель.Наименование Get end)

                // *** End programmer edit section *** (Производитель.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Производитель.Наименование Set start)

                // *** End programmer edit section *** (Производитель.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Производитель.Наименование Set end)

                // *** End programmer edit section *** (Производитель.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроизводительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроизводительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроизводительE", typeof(IIS.Stomatologiya.Производитель));
                }
            }
            
            /// <summary>
            /// "ПроизводительL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроизводительL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроизводительL", typeof(IIS.Stomatologiya.Производитель));
                }
            }
        }
    }
}
