//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stomatologiya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр записи.
    /// </summary>
    // *** Start programmer edit section *** (РегистрЗаписи CustomAttributes)

    // *** End programmer edit section *** (РегистрЗаписи CustomAttributes)
    [AutoAltered()]
    [Caption("Регистр записи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрЗаписиE", new string[] {
            "КодЗаписи as \'Код записи\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Сумма as \'Сумма\'"})]
    [View("РегистрЗаписиL", new string[] {
            "КодЗаписи as \'Код записи\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Сумма as \'Сумма\'"})]
    public class РегистрЗаписи : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаписи;
        
        private System.DateTime fДата;
        
        private string fВремя;
        
        private double fСумма;
        
        // *** Start programmer edit section *** (РегистрЗаписи CustomMembers)

        // *** End programmer edit section *** (РегистрЗаписи CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.Время CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Время Get start)

                // *** End programmer edit section *** (РегистрЗаписи.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (РегистрЗаписи.Время Get end)

                // *** End programmer edit section *** (РегистрЗаписи.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Время Set start)

                // *** End programmer edit section *** (РегистрЗаписи.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (РегистрЗаписи.Время Set end)

                // *** End programmer edit section *** (РегистрЗаписи.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.Дата CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Дата Get start)

                // *** End programmer edit section *** (РегистрЗаписи.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегистрЗаписи.Дата Get end)

                // *** End programmer edit section *** (РегистрЗаписи.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Дата Set start)

                // *** End programmer edit section *** (РегистрЗаписи.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегистрЗаписи.Дата Set end)

                // *** End programmer edit section *** (РегистрЗаписи.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.КодЗаписи CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.КодЗаписи CustomAttributes)
        public virtual int КодЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.КодЗаписи Get start)

                // *** End programmer edit section *** (РегистрЗаписи.КодЗаписи Get start)
                int result = this.fКодЗаписи;
                // *** Start programmer edit section *** (РегистрЗаписи.КодЗаписи Get end)

                // *** End programmer edit section *** (РегистрЗаписи.КодЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.КодЗаписи Set start)

                // *** End programmer edit section *** (РегистрЗаписи.КодЗаписи Set start)
                this.fКодЗаписи = value;
                // *** Start programmer edit section *** (РегистрЗаписи.КодЗаписи Set end)

                // *** End programmer edit section *** (РегистрЗаписи.КодЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (РегистрЗаписи.Сумма CustomAttributes)

        // *** End programmer edit section *** (РегистрЗаписи.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Сумма Get start)

                // *** End programmer edit section *** (РегистрЗаписи.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (РегистрЗаписи.Сумма Get end)

                // *** End programmer edit section *** (РегистрЗаписи.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрЗаписи.Сумма Set start)

                // *** End programmer edit section *** (РегистрЗаписи.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (РегистрЗаписи.Сумма Set end)

                // *** End programmer edit section *** (РегистрЗаписи.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрЗаписиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрЗаписиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрЗаписиE", typeof(IIS.Stomatologiya.РегистрЗаписи));
                }
            }
            
            /// <summary>
            /// "РегистрЗаписиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрЗаписиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрЗаписиL", typeof(IIS.Stomatologiya.РегистрЗаписи));
                }
            }
        }
    }
}
